[versions]
agp = "9.4.0"
coreKtx = "1.19.0"
akkaActor = "2.3.14"
commonsCodec = "1.22.1"
guava = "33.7.1-android"
json4sNative = "4.0.6"
okhttp = "5.5.0"
quicklens = "1.9.15"
scalaParserCombinators = "2.2.0"
scodecCore = "1.11.4"
secp256k1KmpJniAndroid = "0.19.0"
sprayJson = "1.3.6"
recyclerview = "1.4.0"
appcompat = "1.8.0"
currencyedittext = "1.0.0"
zxingAndroidEmbedded = "4.3.0"
nvWebsocketClient = "2.14"
rxscala = "0.27.0"
multidex = "2.0.1"
material = "1.14.0"
web3j = "6.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
akka-actor = { module = "com.typesafe.akka:akka-actor_2.11", version.ref = "akkaActor" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
json4s-native = { module = "org.json4s:json4s-native_2.11", version.ref = "json4sNative" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
quicklens = { module = "com.softwaremill.quicklens:quicklens_2.11", version.ref = "quicklens" }
scala-parser-combinators = { module = "org.scala-lang.modules:scala-parser-combinators_2.11", version.ref = "scalaParserCombinators" }
scodec-core = { module = "org.scodec:scodec-core_2.11", version.ref = "scodecCore" }
secp256k1-kmp-jni-android = { module = "fr.acinq.secp256k1:secp256k1-kmp-jni-android", version.ref = "secp256k1KmpJniAndroid" }
spray-json = { module = "io.spray:spray-json_2.11", version.ref = "sprayJson" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
currencyedittext = { module = "com.cottacush:CurrencyEditText", version.ref = "currencyedittext" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
rxscala = { module = "io.reactivex:rxscala_2.11", version.ref = "rxscala" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
websocket = { group = "com.neovisionaries", name = "nv-websocket-client", version.ref = "nvWebsocketClient" }
web3j = { group = "org.web3j", name = "core", version.ref = "web3j" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
scalaAndroid = { id = "com.soundcorset.scala-android", version = "26.0124.2208" }
